<#
    Switches which copy of the plugin Stream Deck runs.

    Two things are wanted from one plugin folder and they pull apart:

      dev      - a junction, so Stream Deck runs this working tree. Build and
                 restart, and the change is live. No packaging step.
      release  - a real copy installed from dist/*.streamDeckPlugin, which is
                 exactly what a user gets, including whatever .sdignore keeps
                 out of the package.

    Worth being deliberate about, because the two are easy to confuse and the
    confusion is silent: a fixed bug once kept reproducing for an afternoon
    against a sidecar built the previous day, while every rebuild reported
    success. rebuild.ps1 now refuses in release mode for the same reason.

    Run with no arguments to see which mode is active.
#>
param(
    [ValidateSet('dev', 'release', 'status')]
    [string]$Mode = 'status',

    [string]$Root = "C:\Users\dswett\repos\streamdeck-teams-control",
    [string]$Uuid = "com.bad-duck.teamscontrol"
)

$ErrorActionPreference = 'Stop'

$installed = Join-Path $env:APPDATA "Elgato\StreamDeck\Plugins\$Uuid.sdPlugin"
$source = Join-Path $Root "$Uuid.sdPlugin"

function Get-Mode {
    if (-not (Test-Path $installed)) { return 'absent' }
    $link = (Get-Item $installed -Force).LinkType
    if ($link -eq 'Junction') { return 'dev' }
    return 'release'
}

<#
    Whether the code Stream Deck is running was built after the last source
    change. This is the question that matters in either mode, and the one that
    went unasked for an afternoon while a fixed bug kept reproducing.

    Build output is deliberately not considered a source: it is regenerated by
    every build and would always look newer than itself.
#>
function Show-Freshness([string]$builtPath) {
    if (-not (Test-Path $builtPath)) { return }

    $builtAt = (Get-Item $builtPath).LastWriteTime
    $newest = Get-ChildItem (Join-Path $Root 'src'), (Join-Path $Root 'sidecar') -Recurse -File -Include *.ts,*.cs -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '\\(bin|obj|node_modules)\\' } |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1

    if (-not $newest) { return }

    if ($newest.LastWriteTime -gt $builtAt) {
        Write-Host ("  STALE: {0} changed {1}, after the running build ({2})" -f `
            $newest.Name, $newest.LastWriteTime, $builtAt) -ForegroundColor Yellow
    }
    else {
        Write-Host "  up to date with sources" -ForegroundColor DarkGray
    }
}

function Show-Status {
    $current = Get-Mode
    switch ($current) {
        'dev' {
            $target = (Get-Item $installed -Force).Target
            Write-Host "mode: dev (junction)" -ForegroundColor Cyan
            Write-Host "  Stream Deck runs: $target"
            Show-Freshness (Join-Path $installed 'bin\sidecar\TeamsBridge.exe')
            Write-Host "  to publish a change: npm run build; npx streamdeck restart $Uuid"
        }
        'release' {
            $exe = Join-Path $installed 'bin\sidecar\TeamsBridge.exe'
            $built = if (Test-Path $exe) { (Get-Item $exe).LastWriteTime } else { '(missing)' }
            Write-Host "mode: release (installed copy)" -ForegroundColor Green
            Write-Host "  Stream Deck runs: $installed"
            Write-Host "  sidecar built:    $built"
            Show-Freshness $exe
            Write-Host "  to publish a change: npm run pack; .\sidecar\install-local.ps1"
        }
        'absent' {
            Write-Host "mode: not installed" -ForegroundColor Yellow
        }
    }
    return $current
}

function Stop-Plugin {
    Push-Location $Root
    try { npx streamdeck stop $Uuid 2>&1 | Out-Null } catch { } finally { Pop-Location }
    Start-Sleep -Seconds 2

    # Release the sidecar's lock on its own image and on the folder being
    # replaced; Stream Deck respawns it once the plugin is started again.
    foreach ($p in @(Get-CimInstance Win32_Process -Filter "Name='TeamsBridge.exe'" -ErrorAction SilentlyContinue)) {
        Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue
    }
    Start-Sleep -Seconds 2
}

if ($Mode -eq 'status') { Show-Status | Out-Null; return }

$current = Get-Mode
if ($current -eq $Mode) {
    if ($Mode -eq 'dev') {
        # A junction is always live, so there is nothing to refresh.
        Write-Host "already in dev mode." -ForegroundColor Green
        Show-Status | Out-Null
        return
    }

    # Release mode is not self-updating: the installed copy is only as new as
    # the last install. Saying "already in release mode" and stopping is how a
    # stale build goes unnoticed, so this reinstalls instead.
    Write-Host "already in release mode; reinstalling from dist to be sure." -ForegroundColor Cyan
}

if ($Mode -eq 'dev') {
    if (-not (Test-Path $source)) { throw "no plugin folder to link to: $source" }

    # A junction runs the built output, not the sources, so an unbuilt tree
    # would link Stream Deck to a plugin with no code in it.
    $needed = @(
        (Join-Path $source 'bin\plugin.js'),
        (Join-Path $source 'bin\sidecar\TeamsBridge.exe')
    )
    $missing = $needed | Where-Object { -not (Test-Path $_) }
    if ($missing) {
        Write-Host "build output is missing:" -ForegroundColor Yellow
        $missing | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
        throw "run 'npm run build' first"
    }

    Stop-Plugin

    if (Test-Path $installed) {
        # Deleted rather than archived: it is a copy of a package that dist/
        # still holds, and Stream Deck refuses to start with two plugin folders
        # claiming one UUID.
        Remove-Item $installed -Recurse -Force
    }

    # Junction rather than a symlink: directory junctions need no elevation and
    # no developer mode, and Stream Deck follows them either way.
    & cmd /c mklink /J "`"$installed`"" "`"$source`"" | Out-Null
    if (-not (Test-Path $installed)) { throw "could not create the junction" }

    Push-Location $Root
    try { npx streamdeck restart $Uuid 2>&1 | Out-Null } catch { } finally { Pop-Location }
    Start-Sleep -Seconds 6

    Write-Host "switched to dev." -ForegroundColor Cyan
    Show-Status | Out-Null
    Write-Host ""
    Write-Host "Stream Deck now runs the working tree, uncommitted changes and all." -ForegroundColor DarkGray
    Write-Host "Switch back before judging a release: .\sidecar\use-plugin.ps1 release" -ForegroundColor DarkGray
    return
}

# release
$pkg = Join-Path $Root "dist\$Uuid.streamDeckPlugin"
if (-not (Test-Path $pkg)) { throw "no package to install: $pkg  (run 'npm run pack')" }

Stop-Plugin

if (Test-Path $installed) {
    $link = (Get-Item $installed -Force).LinkType
    if ($link -eq 'Junction') {
        # Removing a junction removes the link, not the repo behind it - but
        # only when it is removed as a directory entry, so this is deliberately
        # not a recursive delete.
        & cmd /c rmdir "`"$installed`"" | Out-Null
        if (Test-Path $installed) { throw "could not remove the junction" }
    }
    else {
        Remove-Item $installed -Recurse -Force -ErrorAction SilentlyContinue
    }
}

& (Join-Path $Root 'sidecar\install-local.ps1') -Root $Root -Uuid $Uuid

Push-Location $Root
try { npx streamdeck restart $Uuid 2>&1 | Out-Null } catch { } finally { Pop-Location }
Start-Sleep -Seconds 6

Write-Host "switched to release." -ForegroundColor Green
Show-Status | Out-Null
Write-Host ""
Write-Host "This is the package a user installs. Validate here before shipping." -ForegroundColor DarkGray
